### ISSUE TITLE
Arrange output --nup by columns

### ISSUE THREAD

**Issue by NikoLichi** [DavidFirth/pdfjam#27]
Hi David and/or collaborators,

First of all I want to say that I found this great tool very recently and I love it! Still a lot to explore with but is working well so far for what I need: imposing pdf figures in a grid.

Maybe I missed something but I would like to arrange my plots with the --nup option by column instead of rows. 
I saw this great answer online [https://superuser.com/questions/1075676/merge-glue-exported-pdf-from-spreadsheet-application] but while running the `--column true` option I get and error. Besides, there is not reference in the readme nor in the pdfjam help.

Is this option implemented? if not would be a great to have it.

Thanks for you help.
Niko

**Comment by DavidFirth** [comment]
That `--column true` should work.  It is part of pdfpages, still, I believe.  Because it is part of pdfpages, it is not covered explicitly in the help for pdfjam, other than through the reference there to the pdfpages manual.

I cannot guess why it does not work for you, on your computer -- sorry.  You'll need to debug that for yourself (i.e., read the error message, try `--tidy false`, etc.)
