### ISSUE TITLE
Add a configure script to the package?

### ISSUE THREAD

**Issue by DavidFirth** [DavidFirth/pdfjam#9]
I would like to arrange things in the `pdfjam` source repository so that people can just do the usual

```
./configure
make
make install
```

to make pdfjam available on their own computer.  But I don't know how best to go about setting this up.  (I am not a programmer.)  I would appreciate any offer of help with this.

**Comment by badenh** [comment]
What you are talking about is a makefile, which in itself isn't complicated.
However looking at pdfjam, I'm not sure you need this really - a makefile typically provides some variables and some entries for specific build or execute target behaviour. 
Since this is bundled with TeXLive, you probably only need a makefile for the manual installation case: adding bin to PATH and man1 to MANPATH. I'll add this as a PR.

**Comment by DavidFirth** [comment]
Thanks, Baden.  This (and the associated pull request with minimal Makefile) is helpful input for me.  In view of what you said here, I am inclined now not to bother with this (ie, with the inclusion of a Makefile) --- it seems like overkill, and could even be confusing to some people perhaps.

I'll leave this issue open for another week or two, though, just to see if anyone has further thoughts on it.

**Comment by DavidFirth** [comment]
Decision now made (not to include a Makefile --- for now, at least).

Thanks again for your help with it, Baden.
